### ISSUE TITLE
Include Sugarizer 1.1.0 ?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1420]
See:

https://groups.google.com/forum/m/#!topic/unleashkids/2J4iTJFIyPI

https://github.com/llaske/sugarizer/releases ready!

@llaske is https://github.com/llaske/sugarizer-server/releases not yet ready?

**Comment by llaske** [comment]
Sugarizer 1.1.0 don't need an upgrade of Sugarizer Server 1.0.x to run. Conversely, Sugarizer Server 1.0.x don't need to be upgraded to run Sugarizer 1.1.0.
So just copy/gitpull the new Sugarizer version into the sugarizer directory of your Sugarizer server and it will works.
Since version 1.0 Sugarizer (App) and Sugarizer Server are now separated components, I don't need to upgrade both simultaneously.
