### ISSUE TITLE
Mounting disks ?

### ISSUE THREAD

**Issue by mitra42** [iiab/iiab#1874]
### Expected behavior and actual behavior.
I'd expect that plugging a USB hard drive into the USB port would make it available

### Steps to reproduce the problem.
Plug in USB hard drive 
Look in /media/*

### Specifications like the version of the IIAB, operating system version, or hardware details.
IIABv7, Seagate Hard disk with a NTFS file system

I'm not succeeding in getting hard disks to work on IIAB.
 I've manually added `max_usb_current=1` to `/boot/config.txt` as suggested on https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=101084 but that didn't help.

/etc/usbmount/usbmount.conf also looks correct for NTFS according to various suggestions I found. 

Has anyone worked on this?

**Comment by holta** [comment]
@mitra42 does the top of http://FAQ.IIAB.IO help, where it explains "Can teachers display their own content?"

Short Version:

By default most all external disks/drives/sticks/SD-cards of almost any kind should be auto-mounted in `/library/www/html/local_content` and visible to all (publicly!) at http://box/usb

Please do not rely on this much older/earlier doc which is unmaintained:
https://github.com/iiab/iiab/blob/master/roles/usb-lib/README.rst

**Comment by mitra42** [comment]
Sorry - that helped for USB sticks, but not for disks - the disks aren't getting mounted so they aren't showing up here.

**Comment by holta** [comment]
An NTFS-formatted external disk worked for me a few months ago (or maybe it was 2018) exactly the same way as a USB memory stick / thumb drive &mdash; with all of its content mounting in `/library/www/html/local_content`

That was using an RPi 3 B+ running Raspbian Stretch Lite.  Now of course we favor RPi 4 running Raspbian Buster &mdash; whether the "Lite" version or the "With Desktop" version &mdash; both are common.

What is your exact HW & your exact OS?

**Comment by holta** [comment]
@mitra42 FYI for comparison a USB NTFS hard disk just auto-mounted successfully to `/media/usb0` on IIAB 7.0 pre-release running Raspbian Buster on RPi 4, and its (HDD) content is available publicly over the IIAB/RPi's hotspot, with URL http://box/usb

So I'm unable to reproduce the symptom you describe.

Is it possible your modifications (to `/boot/config.txt` or otherwise?) are interfering with IIAB's default behavior to mount USB disks?

**Comment by mitra42** [comment]
I've got a RPI3, uname -a reports: 
```
Linux box.lan 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux 
```
Which was downloaded from Rasbian in the last few days. Its the desktop version. 
The only change to /boot/config.txt was to add the line to increase max power draw on the USB's, and that was after I started seeing the problem.

**Comment by mitra42** [comment]
The Hard disk was a NTFS drive, since that failed I reformated as a exFAT with no change to behavior

**Comment by holta** [comment]
> The Hard disk was a NTFS drive, since that failed I reformated as a exFAT
> with no change to behavior

Myself I cannot reproduce this.

External (USB) NTFS hard disk auto-mounts within seconds to /media/usb0 on
IIAB 7.0 pre-release on latest Raspbian Buster Lite on RPi 4, as mentioned
above.

**Comment by mitra42** [comment]
Thanks for trying to replicate, let me try reformatting my disk back to NTFS, maybe was a problem with this specific disk.

**Comment by holta** [comment]
FYI likewise with a RPi 3 B+ running the latest IIAB 7.0 pre-release on Raspbian With Desktop: an external USB NTFS hard disk was just now tested to auto-mount to /usb/usb0

There must be something oddly anomalous and/or non-standard about your setup.

Let us know if you can identify what that is.

As this auto-mounting functionality has been tested in very diverse situations (with different external USB disks, etc, in many countries schools) in recent years, where schools rely on it, so that teacher's materials (on thumbdrives and real external drives) appear nearly instantly across the entire classroom, using URL http://box/usb

**Comment by mitra42** [comment]
Will do ....Looks like I dont have a way to format NTFS (can't do on a mac) but I'm trying a few other variations since sounds like problem might be here :-)

**Comment by holta** [comment]
> Will do ....Looks like I dont have a way to format NTFS (can't do on a mac) but I'm trying a few other variations since sounds like problem might be here :-)

Weird.  NTFS is 20+ years old now, so I imagined it would be de facto open, even if exFAT might still be encumbered by patents?

**Comment by mitra42** [comment]
Maybe its because its so old, that its rarely seen - OSX can read NTFS but not write (or format).

I think I nailed it - I found another drive (Toshiba 2TB), and that worked, and then on a hunch I think the problem was power related, switching to different USB power source, and reducing it to just a single drive , and neither keyboard nor display, seemed to fix it even for the first drive, which must just be a power hog. 

Thanks for helping me narrow down the issue

**Comment by holta** [comment]
@mitra42 I'll assume this is resolved as others have not been able to reproduce it, but please re-open and explain as nec?  Thanks!
