### ISSUE TITLE
master broken: box.lan changes to 172.18.96.1 in the browser

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#2067]
### Expected behavior and actual behavior.
When I access box.lan on the my cell phone the url displayed in the browser changes to 172.18.96.1, should remain box.lan

### Steps to reproduce the problem.
install master [and add #2065 NO LONGER NEC, run ./iiab-network NO LONGER NEC], then access box.lan over wifi

### Specifications like the version of the IIAB, operating system version, or hardware details.
think it's nginx related, this line: rewrite ^/$ $scheme://$server_addr/home/; in /etc/nginx/server.conf is forcing the use of the ip address

**Comment by holta** [comment]
@georgejhunt can you take a look at this?

**Comment by jvonau** [comment]
/home should really be defined by the variable {{ iiab_home_url }}

**Comment by holta** [comment]
@georgejhunt: @jvonau suggests you're probably the best person to solve this?

But if not please unassign yourself, Thanks!

**Comment by georgejhunt** [comment]
Function > form for me. But it's true that I've done quite a bit of the
nginx migration.
It comes down to reading docs, and trial and error.
And since it is cosmetic, will be relatively low on my priority list.
You can leave it on my list, until someone appears who will make it a
higher priority.
Sometimes I'm bored, and looking for a small task that might give me a
sense of accomplishment.

**Comment by holta** [comment]
Please review @jvonau's proposed solution at PR #2068.

Thanks all for bringing these many NGINX regressions under control.

We're not there yet (http://minutes.iiab.io) but hopefully St Nick will help ;)
