### ISSUE TITLE
investigate reported WordPress failure on Ubuntu

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#237]
TASK [wordpress : Get the WordPress software] **********************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true,
"msg": "failed to create temporary content file: timed out"}
        to retry, use: --limit @/opt/iiab/iiab/iiab.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=312  changed=57   unreachable=0    failed=1

**Comment by holta** [comment]
@jvonau do you have more context what OS etc were involved?  (fresh install using master presumably?)

**Comment by jvonau** [comment]
[GRS](https://github.com/germanrs?) on [xsce-devel](https://groups.google.com/forum/#!topic/xsce-devel/UQsDAU8So9U) was installing Ubuntu 16.04 and is interested in testing. Reach out to add GRS to this issue?

**Comment by holta** [comment]
@jvonau please resolve if poss?

**Comment by arky** [comment]
This problem is causing Ubuntu, Debian, CentOS builds to fail on Jenkins server.
 
Please consider marking this issue as 'critical' and 'release blocker'. 


==> centos: TASK [1-prep : Checking for ifcfg-WAN file - Can Fail] *************************
==> centos: skipping: [127.0.0.1]
==> centos: 
==> centos: TASK [1-prep : Setting ifcfg-WAN True] *****************************************
==> centos: fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "The conditional check 'has_ifcfg_WAN.stat.exists' failed. The error was: error while evaluating conditional (has_ifcfg_WAN.stat.exists): 'dict object' has no attribute 'stat'\n\nThe error appears to have been in '/opt/iiab/iiab/roles/1-prep/tasks/detected_redhat.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Setting ifcfg-WAN True\n  ^ here\n"}
==> centos: 	to retry, use: --limit @/opt/iiab/iiab/iiab.retry
==> centos: 
==> centos: PLAY RECAP *********************************************************************
==> centos: 127.0.0.1                  : ok=36   changed=7    unreachable=0    failed=1   

==> debian: TASK [1-prep : Find wifi gateway config if present - Can Fail] *****************
==> debian: skipping: [127.0.0.1]

==> debian: 
==> debian: TASK [1-prep : Setting has_wifi_gw based on ESSID if found - Can Fail] *********
==> debian: fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'stdout_lines'"}
==> debian: 	to retry, use: --limit @/opt/iiab/iiab/iiab.retry
==> debian: 
==> debian: PLAY RECAP *********************************************************************
==> debian: 127.0.0.1                  : ok=37   changed=17   unreachable=0    failed=1

**Comment by holta** [comment]
Thanks @arky for the report!

Do these CentOS and Debian ansible issues have anything to do with WordPress?
(If not, can you please consider a new ticket?)

**Comment by holta** [comment]
I'm moved both of @arky's issues to #314 and #315 as they're not WordPress downloading issues (#237 here appears to be a solved issue, insofar as all downloads are sovable!?)

**Comment by holta** [comment]
@jvonau: feel free to re-open this WordPress downloading issue if it's truly a systemic failure?

(Rather than an intermittent/inevitable downloading glitch...)

**Comment by jvonau** [comment]
I feel that the fail to download might be related to the available
bandwidth available at the build location. Might have to state a longer
timeout or add a timeout value if one is not already present.
