### ISSUE TITLE
Do MediaWiki/Moodle/Etc need to output PDF? If so, consider 'apt install texlive' etc?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2866]
@martignoni would you know if [TeX Live](https://en.wikipedia.org/wiki/TeX_Live) is useful with Moodle?

(Though possibly outputting PDF's is less relevant in low-income phone-centric societies?)

Certainly some MediaWiki install instructions recommend this, as well as this excerpt from https://pandoc.org/installing.html#linux :

> "For PDF output, you’ll need LaTeX. We recommend installing TeX Live via your package manager. (On Debian/Ubuntu, apt-get install texlive.)"

Ref:

- #2854

**Comment by martignoni** [comment]
Yes, it is useful for Moodle instances installed on "normal" servers (i.e. with a lot of hard disk space and memory).

However, for small infrasctuctures, it's IMHO an overkill, since the TeXLive distro is quite big (IIRC) and MathJax does very well its job for displaying equations (not in PDF though, but I may be wrong).
