### ISSUE TITLE
Single Line Installer is Down [blocked by campus network]

### ISSUE THREAD

**Issue by yuvrajmakkena** [iiab/iiab#3287]
## Single Line Installer is Down
![image](https://user-images.githubusercontent.com/40199249/177199502-abce2c41-c73f-49c4-9d98-eed0e3b7fa3c.png)

**Comment by holta** [comment]
Hi @yuvrajmakkena !

What ISP (Internet Service Provider) or mobile phone carrier are you using?

**Comment by yuvrajmakkena** [comment]
Hi @holta 
It is blocked by campus network, do we have any other repository?

**Comment by holta** [comment]
> Hi @holta It is blocked by campus network, do we have any other repository?

Hi @yuvrajmakkena thanks for explaining:

1) If they don't block GitHub you can also try to run:

   ```
   sudo curl https://raw.githubusercontent.com/iiab/iiab-factory/master/iiab > /usr/sbin/iiab
   sudo chmod 0744 /usr/sbin/iiab
   sudo iiab
   ```

2) However it will try to download several pieces of IIAB from download.iiab.io so the problem is probably not fully solved!

3) Can you please ask your campus IT department to unblock https://download.iiab.io and anything that ends in *iiab.io* ?  

   What university or school is this &mdash; I ask because this is a humanitarian education project &mdash; and we should try to make sure they understand that!

**Comment by jvonau** [comment]
> However it will try to download several pieces of IIAB from download.iiab.io so the problem is probably not fully solved!

Once upon a time there was code to detect and record that situation.

**Comment by yuvrajmakkena** [comment]
- Observations
  - I tried to Configure Manual Proxy in Firefox which VPN users outside campus use to get into campus network.(Intranet)
           ![image](https://user-images.githubusercontent.com/40199249/177466743-f6eeac28-e882-4f2e-a97f-8760e157aacd.png)

  - Its working now.
  
      ![image](https://user-images.githubusercontent.com/40199249/177466186-7a02895f-f418-4b43-bb7b-6da331d8d664.png)

**Comment by jvonau** [comment]
Think you might want to export those proxy setting to your environment as curl, apt, and ansible don't know about the firefox proxy setting. Depends on the desktop used as to where the gui-tool is located 'settings' -> 'network' -> 'Network Proxy' maybe.

**Comment by holta** [comment]
@yuvrajmakkena progress?

(Let us know how you make out!)

**Comment by holta** [comment]
Thanks @yuvrajmakkena for making contact.

Let us know if further problems arise.
