### ISSUE TITLE
Unable to download zim file from the admin console.

### ISSUE THREAD

**Issue by rickgurmet** [iiab/iiab#3387]
I logged in to the admin console of the IIAB to download some zim files but unfortunately, I was not able to download some of the zim files. I got a pop-up alert message saying **"INST-ZIMS FAILED and reported Zim File crashcourse_en_all2022-07 not found in Cmd INST-ZIMS"** .
The alert pops up for many zim files like the crash_course, wikihow, etc.

![issue_1](https://user-images.githubusercontent.com/87523939/193288792-2657d9bc-94b3-45fc-b12e-1625b4ba543d.png)

I installed the latest IIAB onto an Intel NUC (just a few days back)

iiab-diagnostics: http://sprunge.us/3fyNhH?bash

**Comment by tim-moody** [comment]
Just tried this on a VM. Did not get the popup and download is proceeding.

Kiwix has the file at https://download.kiwix.org/zim/other/crashcourse_en_all_2022-07.zim

**Comment by holta** [comment]
> INST-ZIMS FAILED and reported Zim File crashcourse_en_all_2022-07
> not found in Cmd INST-ZIMS

Is the above error... exactly the same as what happens... when the IIAB is offline?

[This issues seems likely caused by Internet configuration changes being discussed on separate ticket...]

- #3385

**Comment by tim-moody** [comment]
from iiab-diagnostics

```
3348 Sep 18 14:41:56 box IIAB-CMDSRV[1205]: IIAB-CMDSRV : Received CMD Message INST-ZIMS {"zim_id":"db930556-75d9-f82c-e27e-17f1988b8a9f"}.
3349 Sep 18 14:42:10 box IIAB-CMDSRV[1205]: IIAB-CMDSRV : Error: Zim File crashcourse_en_all_2022-07 not found in Cmd INST-ZIMS.
```

This was a few days ago. Could the zim catalog be out of date?

>Is the above error... exactly the same as what happens... when the IIAB is offline?

INST-ZIMS requires an internet connection to run.

**Comment by holta** [comment]
@rickgurmet Does this error occur after (1) confirming Internet then (2) fully rebooting?

> This was a few days ago. Could the zim catalog be out of date?

@rickgurmet Please also click http://box.lan/admin **> Install Content > Refresh Kiwix Catalog** to be sure:

![image](https://user-images.githubusercontent.com/2458907/193298047-c64faa88-e966-4eef-9ae0-5712d08eae1a.png)

**Comment by tim-moody** [comment]
After studying this a bit, I think this could happen if the server thinks it has an internet connection but doesn't. I thought this error occurs when a zim id is not in the catalog, but that error message is slightly different. This is the one that occurs when an attempt is made to open the download file to verify that it exists and that fails.

**Comment by holta** [comment]
> I think this could happen if the server thinks it has an internet connection but doesn't.

That was my fear (:

(As Internet connections come and go, minute-by-minute, for all sorts of different reasons ;)

**Comment by tim-moody** [comment]
For each command that it receives CMDSRV checks to see if it requires an internet connection and if so does a test for one. So the time between the test and this error message would probably be milliseconds and certainly less than a few seconds.

I'm more worried that the reconfig of networking makes it think there is an internet connection when there isn't or there is a flaw to the test logic.

The test is socket.create_connection(("neverssl.com", 80))

**Comment by tim-moody** [comment]
On a rpi4 with no internect connection I logged into the hotspot, selected the same zim and clicked install. The message I got was

INST-ZIMS FAILED and reported Internet is Required for this Command but is Not Available.

**Comment by tim-moody** [comment]
The original request was on Sept 18 according to the log. I wonder what happens if a download is started when an internet connection is available and then the machine is shut down for some reason. Now when it is started again the job will be restarted, but I don't think it will hit the code that returns this error.

**Comment by holta** [comment]
@rickgurmet can you run `sudo iiab-diagnostics` and post the **sprunge.us** URL here, so that we have _up-to-date_ log file info to understand better?

Please if possible, Thanks!

**Comment by rickgurmet** [comment]
@holta here is the strunge.us URL  [ http://sprunge.us/5oa3JZ
](http://sprunge.us/5oa3JZ)

I tried again after selecting a few zim files together, and it showed me the same pop-up, but when I installed them individually, it worked for most of it. I think because the system is not able to handle the request all at a time, it does the pop-up, and the system is unable to download the files.

It was interesting to see that, when you select a few zim files to install, sometimes you don't see pop-ups for all the zims, and one of the zim files might be downloading. (as I checked the job status, it showed me there).

Also when there are zim files already downloading and when you try to install another zim file, it also shows the same pop-up sometimes.

**Comment by holta** [comment]
Many thanks @rickgurmet for the detailed report just above, which will hopefully help Tim a lot!

**Comment by tim-moody** [comment]
>I tried again after selecting a few zim files together, and it showed me the same pop-up, but when I installed them individually, it worked for most of it. I think because the system is not able to handle the request all at a time, it does the pop-up, and the system is unable to download the files.

@rickgurmet  I think you are right.

The following tests are done:

- check for internet connection: succeeded
- check that zim is in catalog: succeeded
- check that download url in catalog exists: failed, but was a false negative

The chances of the last test truly failing are small if the first two succeed unless either Kiwix or your connection are too busy. I think I should eliminate this test and let the download fail in the rare case that the url is wrong. 

CMDSRV will only try to download a limited number of zims at a time. More requests are scheduled but not started. However this check for a connection is tried no matter how many zims are currently downloading, so it may fail even though it would succeed later.

There is another possibility, that Kiwix is busy. @holta has reported that less used zims sometimes fail to download when many requests are made.

In either case I think removing the url check that causes this popup would help the situation. Comments?

**Comment by holta** [comment]
Thanks @tim-moody for having very carefully explained.

A couple tiny questions, trying to understand a bit better:

> check that download url in catalog exists: failed, but was a false negative

Is it checking online, that the URL is "live" ?

(Or do you mean checking the URL locally somehow, and if so roughly how?)

> CMDSRV will only try to download a limited number of zims at a time. More requests are scheduled but not started. However this check for a connection is tried no matter how many zims are currently downloading, so it may fail even though it would succeed later.

Ladakh's ISP(s) have proven quite unreliable, behaving quite differently from other ISP's worldwide.  (I don't know if this is related, but it might be?)  An example is:

- #3358

FWIW the i3 NUC in question here should (generally!?) not suffer from the serious thrashing issues (during content downloads) that we experienced often on comparatively "weak" (easily overwhelmed) machines like Raspberry Pi's over the years.

> There is another possibility, that Kiwix is busy.

Do you mean the slow redirect(s) from download.kiwix.org/zim/* URL's to the actual mirror site &mdash; which indeed can sometimes take many seconds &mdash; before the actual download begins?

> In either case I think removing the url check that causes this popup would help the situation. Comments?

1. Anything that improves the situation, great.

2. Alongside: Can error messaging convey a few more details, to help us (and local operator) analyze + understand root cause(s) in future?

**Comment by tim-moody** [comment]
>Is it checking online, that the URL is "live" ?

attempt to make a url connection to target  without starting a download (rc = urllib.request.urlopen(downloadSrcFile)

>Do you mean the slow redirect(s) from download.kiwix.org/zim/* URL's to the actual mirror site — which indeed can sometimes take many seconds — before the actual download begins?

This is speculation, but yes this could be involved if it causes a timeout.

>Anything that improves the situation, great

tradeoff is that a stale catalog will only be caught when download fails

>Can error messaging convey a few more details

can't report more than we know - connection failed.

**Comment by holta** [comment]
> tradeoff is that a stale catalog will only be caught when download fails

If the local Kiwix catalog is more than a week-old[*] should a pop-up communicate that upon login to Admin Console?

e.g. advising them to click **Install Content > Refresh Kiwix Catalog** ?

[*] Or "more than a month-old" e.g. if "more than a week old" is considered much too intrusive?

**Comment by tim-moody** [comment]
>If the local Kiwix catalog is more than a week-old[*] should a pop-up communicate that upon login to Admin Console?
e.g. advising them to click Install Content > Refresh Kiwix Catalog ?
[*] Or "more than a month-old" e.g. if "more than a week old" is considered much too intrusive?

been there for a long time; advises if more than a month. You should try the Admin Console sometime so you know how it works.

**Comment by holta** [comment]
My point (in my opinion) is that a month is too long.

A week-or-so would be a much more useful timeframe, in my opinion.

Conversely people who click **Install Content > Refresh Kiwix Catalog** often (like me) effectively don't contribute to product improvement for newcomers (who need this information most).

**Comment by holta** [comment]
Others would argue that "Refresh Kiwix Catalog" should be fully automatic during Admin Console login.

I'm not sure I would go that far.

But I see the validity in that proposition (raw simplicity, in fact what people want, rather than learning curve / complexities).

**Comment by holta** [comment]
> Others would argue that "Refresh Kiwix Catalog" should be fully automatic during Admin Console login.

e.g. if the local Kiwix catalog is more than 24h old (or whatever timeframe is set).

**Comment by holta** [comment]
> > Others would argue that "Refresh Kiwix Catalog" should be fully automatic during Admin Console login.
> 
> e.g. if the local Kiwix catalog is more than 24h old (or whatever timeframe is set).

So long as it's reliable, it's very likely this-or-similar is what people want in 2022+.  (Half a decade later with fast Internet connections nearly ubiquitous among people provisioning IIAB around the world, the entire task is usually done in much less than a minute.)

e.g. if this can be made reliable, likely best with either a pop-up or notification within/on Admin Console's regular login screen (a few IIAB implementers still have slowpoke Internet connections) to announce something like:

```
Your Kiwix catalog appears more than 48h out-of-date.
Please wait as a new Kiwix catalog (~20 MB) is being downloaded.
```

Hopefully some such forward-looking UX can be considered?  If so, some staleness timeframe would of course need to be chosen (24h or 48h or 72h or whatever!)

**Comment by tim-moody** [comment]
The current workflow was predicated on an assumption that zims were updated on a monthly basis and a catalog published. I have been following the catalog for a couple of days and have seen it change 3 or 4 times a day by a change in perhaps a single zim.

I think the best approach would be to show the date of the catalog on the zim download screen so that users can decide when to refresh, rather than burdening every login with a download, which will increase the amount of time until the screen becomes active.

The other point is that if the date of a zim the user wants to download is more than a month previous, then there could be a more recent version.

**Comment by holta** [comment]
> change 3 or 4 times a day by a change in perhaps a single zim

That's my impression as well.

> show the date of the catalog

Great idea in general.

Personally I strongly agree.

> burdening every login

Personally I think the overall calculus could use rethinking:

1) Downloading ~20MB takes less than 1 second on many modern connections.  Almost imperceptible among those whose explicit goal is in fact to provision many gigabytes with a reasonably speedy connection.
2) Especially in comparison to the "cognitive load" of having to {read a busy user interface, try to understand it when English is not your native language, make a decision or guess as to what is best, click, acknowledge it really happened} will typically incur more than 10x to 100X more "cognitive load," certainly among new people.
3) My own recommendation is not to download every login.  But to think about some kind of automated download every 24h or 48h or 72h or whatever.  It's just an idea, to reduce the "cognitive complexity" of learning a new UX/UI as everyone appears to want.  There may be better ideas.

**Comment by holta** [comment]
Lots of thoughtful reflections during today's call (http://minute.iiab.io).

While the entire job ([/usr/bin/iiab-get-kiwix-cat](https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/templates/utilities/iiab-get-kiwix-cat) which uses [get_kiwix_catalog_rootxml.py](https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/templates/scripts/get_kiwix_catalog_rootxml.py) and [get_kiwix_catalog_libxml.py](https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/templates/scripts/get_kiwix_catalog_libxml.py)) generally completes in 1-to-2 seconds, even on a slow VM (almost imperceptibly, crying out for some kind of automation to eliminate the pop-up UX entirely...)

...the challenge is that this same command can unfortunately take 10-to-20 seconds on a Raspberry Pi 4, after the nearly instantaneous download (~4.7 MB https://library.kiwix.org/catalog/root.xml usually takes less than 1s to download).  As what takes time is converting that XML to JSON etc, to put the ~3.5 MB /etc/iiab/kiwix_catalog.json into place.

While I wish this 10-20 second job could be run automatically every ~24h in the background, enabling newbie implementers to get the very latest ZIM files with nothing standing in their way, it turns out that's tricky to make happen gracefully, before displaying the new Kiwix catalog's contents in http://box.lan/admin **> Install Content > Get ZIM Files from Kiwix**

So we agreed to the easy/quick improvement of using the existing pop-up staleness warnings, but educating the operator/implementer much more promptly (e.g. if `/etc/iiab/kiwix_catalog.json` appears to be stale by 3+ days, i.e. if it's out-of-date by 72+ hours).  Instead of waiting 30+ days before alerting them to their very stale Kiwix catalog.

_Conclusion: The latest ZIM file choices should become much more easily discoverable with this change &mdash; as most everyone wants &mdash; and especially new people trying to navigate the Learning Curve of a new UX/UI_ :fast_forward:

**Comment by holta** [comment]
The change from 30 days to 3 days is done:

- PR iiab/iiab-admin-console#514

(for Admin Console's pop-up alert about `/etc/iiab/kiwix_catalog.json` growing stale)

**Comment by holta** [comment]
@rickgurmet can you reconfirm the next time you install IIAB?

Thanks please !

**Comment by rickgurmet** [comment]
@holta I can install it in a few days for a test and check everything. I'll let you know soon if there are any issues.

**Comment by holta** [comment]
Many thanks @rickgurmet.

**Comment by holta** [comment]
@rickgurmet

10 weeks later let's close this if these issues are now under control, Thanks!
