### ISSUE TITLE
Asterisk fails to load on Debian 11 as before:

### ISSUE THREAD

**Issue by EMG70** [iiab/iiab#3673]
### Expected behavior and actual behavior:
Full installation with Freepbx installed and enabled
![IMG_1820](https://github.com/iiab/iiab/assets/52469992/5bd3f541-3ef6-4884-b468-c85803f68ecc)
 
### Steps to reproduce the problem:
Retried several times.
### IIAB version, OS version, hardware details:
![IMG_1822](https://github.com/iiab/iiab/assets/52469992/b8c4eec8-2fc6-44a3-9236-360a9769c5f2)

### Please run the `iiab-diagnostics` command, to generate a URL summarizing your IIAB configuration, for volunteers seeking to help you: (Include that short URL here, Thanks!)
http://sprunge.us/4K56PQ?en

**Comment by holta** [comment]
Possibly IIAB's Asterisk patch for Raspberry Pi is no longer necessary?  (Or needs a quick fix?)

Certainly FreePBX 17 pre-releases will run on Debian 12 very shortly — according to these recent announcements:

- #3556

**Comment by holta** [comment]
> Possibly IIAB's Asterisk patch for Raspberry Pi is no longer necessary? (Or needs a quick fix?)

Here's `install_prereq.diff` used with `when: asterisk_rpi_patch` that needs refining (or replacing?)

https://github.com/iiab/iiab/blob/acf125f46d3eff3ac7550faeb3d00711d73131a6/roles/pbx/files/install_prereq.diff#L1-L16

**Comment by holta** [comment]
Workaround for Debian 11 on non-RPi for now:

Set `asterisk_rpi_patch: False` in [/etc/iiab/local_vars.yml](https://wiki.iiab.io/go/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it?)

**Comment by EMG70** [comment]
Installed & Tested OK with asterisk_rpi_patch :False

**Comment by holta** [comment]
It appears `roles/pbx/files/intall_prereq.diff` is no longer relevant, as a result of...

> install_prereq: Fix dependency install on aarch64.
Fixes dependency solutions in install_prereq for Debian aarch64
platforms. install_prereq was attempting to forcibly install 32-bit
armhf packages due to the aptitude search for dependencies.

...merged on 2023-08-14 here: https://github.com/asterisk/asterisk/commit/6a55551c5cceb01e464a4defcb836684e7709920
- https://github.com/asterisk/asterisk/pull/38
- https://github.com/asterisk/asterisk/commits/master/contrib/scripts/install_prereq

...and now part of Asterisk 20 and 21, resolving the original issue:

- https://github.com/asterisk/asterisk/issues/37

**Comment by holta** [comment]
Should now be resolved by:

- PR #3674

Thanks @EMG70 for the bug report!
