### ISSUE TITLE
web interface to upload books into Calibre 3.16 - how to make it work?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#660]
Error msg in browser:
```
Failed to upload the file: SAMPLEBOOK.pdf
You must be logged in to make changes to the library

Failed to communicate with "/cdb/add-book/2/n/SAMPLEBOOK.pdf/calibre", with status: [403] Forbidden

Anonymous users are not allowed to make changes
```
Is this more serious that a permissions issue, when the above directory (/cdb) does not exist on Raspbian 2017-11-29 where Calibre 3.16 is installed?

In any case, https://calibre-ebook.com/whats-new says:
```
New features [in Calibre 3.16]

Content server: Allow adding and deleting of books using the web interface

Use the + icon in the top bar of the book list to add new books and the trash icon in the top bar of the book details page to a delete a book. Note that only authenticated users are allowed to perform these actions, so you have to setup user accounts for the server to use these features.

**Comment by holta** [comment]
This had looked *extremely* promising:

- Calibre Desktop Application -> Preferences -> Sharing over net -> User accounts -> (add Admin/changeme as username/password)
- systemctl restart calibre-serve

But it did not work (the http://box:8080 error remains the same, as pasted in above, on IIAB 6.5/master on Raspbian Desktop 2017-11-29...)

**Comment by tim-moody** [comment]
I would be inclined to believe it when it says you are not logged in. The directory is probably defined in apache and not physical. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: A Holt <notifications@github.com> Date: 1/28/18  3:57 PM  (GMT+07:00) To: iiab/iiab <iiab@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [iiab/iiab] web interface to upload books into Calibre 3.16 - how to make it work? (#660) 
This had looked extremely promising:

Calibre Desktop Application -> Preferences -> Sharing over net -> User accounts -> (add Admin/changeme as username/password)
systemctl restart calibre-serve

But it did not work (the http://box:8080 error remains the same, as pasted in above, on IIAB 6.5/master on Raspbian Desktop 2017-11-29...)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iiab/iiab","title":"iiab/iiab","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iiab/iiab"}},"updates":{"snippets":[{"icon":"PERSON","message":"@holta in #660: This had looked *extremely* promising:\r\n\r\n- Calibre Desktop Application -\u003e Preferences -\u003e Sharing over net -\u003e User accounts -\u003e (add Admin/changeme as username/password)\r\n- systemctl restart calibre-serve\r\n\r\nBut it did not work (the http://box:8080 error remains the same, as pasted in above, on IIAB 6.5/master on Raspbian Desktop 2017-11-29...)"}],"action":{"name":"View Issue","url":"https://github.com/iiab/iiab/issues/660#issuecomment-361047826"}}}

**Comment by floydianslips** [comment]
I created a user and logged in as the user and was able to add content. It is not the ideal way probably but it worked. 
create user
calibre-server --userdb /location you want the userdb/users.sqlite --manage-users

calibre-server --port 8080 /library/calibre/ --userdb /location of newly created userdb/users.sqlite --enable-auth

systemctl start calibre-serve.service

You will need to log in using the newly created credentials in a pop up window in the browser, but you can use the new upload button.

**Comment by holta** [comment]
@floydianslips saved the day, at several Mexican schools, thank you.

FYI I used /library/calibre/users.sqlite

And I created these 2 users:

- box/box (for kids)
- Admin/changeme (for teachers)

**Comment by holta** [comment]
Aside: Calibre's client software is quite incredible (Mexican teachers want to use it on Raspbian Desktop and Windows etc!) BUT they need to be warned that it is configuring web users in the wrong place(s) for IIAB:

- /home/pi/.config/.../calibre-server.sqlite
- /root/.config/.../calibre-server.sqlite

So I am asking teachers to stick with Admin/changeme when logging into http://box:8080 for now.  Also the iiab-menu file needs to be fixed from port 8010 to 8080 within /opt/iiab/iiab-menu/config.json

**Comment by tim-moody** [comment]
changing /opt/iiab/iiab-menu/config.json will only work before first install and will block git pulls. after change /library/www/html/iiab-menu/config.json.

if idmgr is gone for good, then we could default to 8080.

**Comment by holta** [comment]
Keeping this tkt open so we can try to:
- Automate (with Ansible) creation of usernames/passwords:
  - box/box
  - Admin/changeme
- Revise port 8010 to 8080 in /opt/iiab/iiab-menu/config.json (and hence /library/www/html/iiab-menu/config.json) — is it possible/realistic to read this variable from local_vars.yml during installation?
- Is it possible to get Calibre's client software to modify our own /library/calibre/users.sqlite instead of its default in /home/pi/.config/.../calibre-server.sqlite or /root/.config/.../calibre-server.sqlite ?
- Explore why http://box/books doesn't quite work as http://box:8080 does

**Comment by holta** [comment]
Essential but Evolving as part of #747 -> #830 (& #816)
