### ISSUE TITLE
hostapd config

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#718]
why are there two config files that are nearly identical?
hostapd.conf and iiab.hostapd.conf

**Comment by holta** [comment]
Problems getting the internal WiFi AP (hostapd) enabled on new IIAB installs?

@floydianslips & @kananigit also — had such problems in the past month.

Until this is solved properly, here are workarounds documented in #655:
- `cd /opt/iiab/iiab; ./iiab-network`
- `systemctl enable hostapd`

**Comment by jvonau** [comment]
@tim-moody   Given that hostapd.conf is an ansible template that is populated only once during iiab-install or iiab-network is run once some other method is used to edit hostapd.conf knowing what the starting point was post ansible becomes more difficult. Just an easy method to have backup copy around that is pre-populated with the values that were declared at ansible runtime.
@holta  Post or sent some logs and I will have a look. Phoning the doctor and saying it hurts here does not provide enough data to solve the problem. I suspect that the install is reporting appliance mode due to some change that was introduced after I wrote routine for the 'keep wifi available as upstream' that you requested.

**Comment by holta** [comment]
Clarif of @tim-moody's observation &mdash; these 2 files in the repo are different:

- [roles/network/templates/hostapd/hostapd.conf.j2](https://github.com/iiab/iiab/blob/master/roles/network/templates/hostapd/hostapd.conf.j2) (689 bytes)
- [roles/network/templates/hostapd/iiab-hostapd.conf.j2](https://github.com/iiab/iiab/blob/master/roles/network/templates/hostapd/iiab-hostapd.conf.j2) (636 bytes, for backup / what was discovered e.g. if you have more than 1 wireless interface?)

**Comment by holta** [comment]
On the call we discussed renaming iiab-hostapd.conf.j2 to iiab-hostapd-discovered.conf.j2 (or some such) but in the end decided against this renaming (as the 2 files to handle separate logic, either/appropriate one is copied into a single final destination file...)
