### ISSUE TITLE
Nodogsplash Captive Portal requires internet connection [try dnsmasq approach?]

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#826]
see nodogsplash/nodogsplash#154

**Comment by holta** [comment]
Refs #412 #575 #597 #608

**Comment by holta** [comment]
@m-anish is currently reviewing https://github.com/nikosft/captive-portal/blob/master/captive_portal.py with @tim-moody, as a possible alternative Captive Portal &mdash; for new ideas at least &mdash; to break this log jam?

As usual testing of Android-and-similar against RPi servers is the key, and they look to be making progress here...

**Comment by holta** [comment]
Chat Excerpt:

Anish: https://github.com/nikosft/captive-portal/blob/master/captive_portal.py
Tim: have you tried it?
Anish: so it is fairly simple script.  it works when there is internet on WAN IF
Tim: so does nodogsplash, but that is not our case
Anish: (or basically when DNS resolves).  yeah...  but i think we can use the iiab flag to do proper iptables redirecting.  we can even make is dynamic.  as it is fairly simple python code.  iiab internet_accessible flag
Tim: I think we need to emulate the traffic to test for internet by different devices
Anish: yea, agree.  this is not wispr or anything like that compliant (if there is such a thing)
Tim: I did a wireshark capture of nodogsplash with WAN internet (works) and without (doesn't work)
Anish: but offers an easy solution to a complex-ish problem...  tim, i think the difference here might be that it is just a few lines of python code, that we can expand and build on without consulting the remote corners of the internet for scarce documentation :)
Tim: I have been through nearly 10 approaches that are 'supposed to work', none works without an internet connection. I agree that the simplicity is a plus. BTW, there's another one in python used by kiwix's pi-box. it doesn't work for android either.
Anish: this is essentially the redirect it does...

-A PREROUTING -i br0 -p tcp -m tcp --dport 80 -j DNAT --to-destination 172.18.96.1:9090

Tim: Anish: do you have the wherewithal to analyze my wireshark captures...  The problem happens before the redirect. You only get to that stage if the device decides it is a captive port situation and so far for me it never does unless dns works
Anish: yeah.  so.. maybe we can have a dynamic bind rule based on whether internet works.  we could do (1) dns blackhole if no internet  or (2) this if there is internet.  because dns blackhole works everytime ... just that it will never redirect to anything on the internet
Tim: There are different test urls for each device and often different for different releases, say of android.  It feels to me like android expects some wan traffic to return expected results. remember that captive portal is not really our use case. it is for regulating traffic to an existing gateway, not for capturing traffic on a lan. we need to be able to fake the expected returns and then grab it. I tried look at the android source code to see what it expects, but got stuck.
Anish: hm.  tim, if you have an android device and an iiab nearby, can you test this quickly?
Tim: I can send you the wireshark dumps
Anish: it is just a simple py script.  i use an oldschool nokia phone
Tim: I have three generations of android devices for this very purpose
Anish: heh. tim, does dns-blackhole work with android?
Tim: so what is the test? start iiab on rpi and run the script?
Anish: yes.  make sure the rpi has internet on WAN.  and connect on LAN.  and try and access something over http.  basically port 80
Tim: OK need to boot
Anish: meanwhile I'll look at how to manage bind from python
Tim: we are switching to dnsmasq to make that part easier
Anish: nice!  so far we are on bind still, right?
Tim: it's already in master
Anish: (oh, enabled?)  i did see a dnsmasq role
Tim: Jerry can tell you how to enable. I think I disabled bind and enabled dnsmasq in local vars, but there's another parameter I need to hunt for.
Holt: Jerry can clarify if this is still a relevant approach to dealing with dnsmasq etc vars: https://github.com/iiab/iiab/pull/699
...
Tim: Anish: captive_portal.py did not work for me
Anish: tim you edited the contents inside.. like network interface?

**Comment by holta** [comment]
Very Promising News from @m-anish :

Tim see https://github.com/m-anish/named_redirect whenever you get a chance
python3 setup.py install
named_redirect
this should selectively enable/disable dns_jail based on internet presence/absence
it needs a few files... dns.blackhole.empty (which is basically an empty file) and dns.blackhole.jail
then named-iiab.conf.nojail and named-iiab.conf.jail
please check the proper paths of these files in the script, and make sure the files are present before you run... 
i'll test it at my end
i think in conjunction with the other python script, this should provide a working captive portal which could adapt to different kinds of connectivity situations. 
this script may anyway be useful if one is gonna use nodogsplash as well
the code is early and raw... but i think it works
you can launch dns_redirect with the -v and -vv flags as well to get more debug info

Tim responded: https://github.com/iiab/iiab/blob/master/roles/network/templates/named/named.blackhole

**Comment by holta** [comment]
New Captive Portal prototype from Anish:

Jerry Tim see: https://github.com/iiab/iiab/compare/master...m-anish:captive_portal?expand=1
(ignore the node-red and mqtt [Mosquitto] parts)
i've done basic testing and it seems to work
i'll be back (tm) later and do more testing :) 
the implementation is very early stage.. but it works, and you might have to play around with the other dns_jail stuff, that's handled separately...
i'm super tight on schedule, so I dont know how much time i have to properly hash this into a PR, but all the needed code and scripts are not there
and we'll need a good captive portal template

**Comment by holta** [comment]
Please see @jvonau's PR #870 building on @m-anish's Captive Portal prototype.  @jvonau wants to see if he can get dnsmasq to do the same job as named does with the blackhole method.

**Comment by holta** [comment]
Thanks to @arky & @tim-moody who clarify that Nodogsplash would appear to work offline with OpenWrt — thereby circumventing problems with OS's like Android 6+ which confuse users and block connecting to content by default — when they do not detect "real" Internet:

https://github.com/nodogsplash/nodogsplash/issues/261
https://github.com/nodogsplash/nodogsplash/issues/249
https://github.com/nodogsplash/nodogsplash/issues/154

**Comment by holta** [comment]
CLARIF that @arky's ongoing work depends on dnsmasq more than Nodogsplash, and is largely based on:

https://github.com/LibraryBox-Dev/LibraryBox-core

FYI @arky uses a separate router running OpenWrt next to the RPi 3 (B+ ?) to achieve basic functionality like a Captive Portal.

**Comment by holta** [comment]
@arky clarifies... OpenWrt [devs indicate] that adding this line to dnsmasq configuration [should] create [Captive Portal] style traffic redirect:
```
address=/#/ip_address_of_iiab
```
@jvonau clarifies... that is exactly what [IIAB's `dns_jail_enabled` variable] does:
https://github.com/iiab/iiab/blob/master/vars/local_vars_medium.yml#L54-L55

**Comment by holta** [comment]
@tim-moody please re-open this if it's still nec!

Others claim this is not an issue: https://github.com/nodogsplash/nodogsplash/issues/154#event-1888947321
